version: "3.9"

services:
  app:
    image: django
    pull_policy: never
    container_name: django
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/mysite
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
